build: Deploy docs to github pages with mkdocs
openfoodfacts/openfoodfacts-infrastructure pull request #158
Opened 2022-11-09 07:16 UTC by sumit-158

### What
- Deploy docs to github pages with mkdocs

### Screenshot
![image](https://user-images.githubusercontent.com/96618001/200763817-b316caac-3945-4ddf-8d11-b13805533792.png)

### Fixes bug(s)
- #148

2022-11-09 07:20 UTC, sumit-158 commented
@alexgarel Ready to review, also two warning of broken links
![image](https://user-images.githubusercontent.com/96618001/200764454-afbf964c-92d2-48c4-b47b-118fe3b1b115.png)

2022-11-09 09:38 UTC, alexgarel requested changes
Really cool.

Some fix needed though :-)

For the broken links, you can fix them, it's just a matter of "s", real path is `2021-12-21-disk-extension.md`

2022-11-09 09:38 UTC, alexgarel commented on docs/README.md
> +# OpenFoodFacts Infrastructure
we should not move README.md but create an index.md it on the fly, fixing the links.

Taken from https://github.com/openfoodfacts/openfoodfacts-server/blob/main/scripts/build_mkdocs.sh:

```bash
# copy README.md as the index but change links starting with ./docs/ to ./
sed -e 's|(\./docs/|(./|g' README.md > docs/index.md
```

2022-11-09 09:38 UTC, alexgarel commented on .github/workflows/generate-docs.yml
> +        run: pip install mkdocs-material
we should also install `mdx_truly_sane_lists` otherwise many documents won't render well

(python markdown lib developper has a very strict interpretation of list indentation, which does not correspond to usage).

2022-11-09 09:38 UTC, alexgarel commented on mkdocs.yml
> +      permalink: "#"
also add mdx_truly_sane_lists (see comment about installation):

```suggestion
      permalink: "#"
  # this one allow to have two space indentation
  # counts as nested list
  - mdx_truly_sane_lists
```

2022-11-09 13:55 UTC, sumit-158 commented on docs/README.md
> +# OpenFoodFacts Infrastructure
Thankyou !

2022-11-09 13:55 UTC, sumit-158 commented on .github/workflows/generate-docs.yml
> +        run: pip install mkdocs-material
Indeed

2022-11-21 13:43 UTC, alexgarel approved these changes

2022-11-21 13:53 UTC, merged